// <auto-generated />
namespace WorkApplications.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class RejoinedVerseTables_AddedTranslationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RejoinedVerseTables_AddedTranslationId));
        
        string IMigrationMetadata.Id
        {
            get { return "201312022003268_RejoinedVerseTables_AddedTranslationId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
