// <auto-generated />
namespace WorkApplications.Migrations.Bible
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class TwoPartTextAndExtraHeading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TwoPartTextAndExtraHeading));
        
        string IMigrationMetadata.Id
        {
            get { return "201408291945350_TwoPartTextAndExtraHeading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
